# Kairo dev cleanup — removes build caches and ephemeral artifacts.
# Safe to run anytime: everything here is regenerated by `npm run tauri dev`.
$ErrorActionPreference = "SilentlyContinue"

$targets = @(
  "$PSScriptRoot\..\src-tauri\target",   # Rust build cache (GBs)
  "$PSScriptRoot\..\dist",               # Vite build output
  "$PSScriptRoot\..\.qodo"               # empty plugin dir
)

# Close a running dev-built app so it stops locking target/
Get-Process kairo -ErrorAction SilentlyContinue | Where-Object { $_.Path -like "$env:USERPROFILE\.kairo-dev\*" -or $_.Path -like "$PSScriptRoot\..\src-tauri\target*" } | Stop-Process

foreach ($t in $targets) {
  if (Test-Path $t) {
    Remove-Item -Recurse -Force $t
    Write-Host "removed $t"
  }
}

$before = (Get-PSDrive C).Free
Write-Host ("Free space now: {0:N1} GB" -f ($before / 1GB))
Write-Host "Note: node_modules is kept. Run `npm install` only if you deleted it manually."
