/**
 * Dev-only fixtures mirroring real Vault data (trimmed). Used by the
 * `?mock` browser harness so pages render without the Tauri backend.
 */
import type {
  Application,
  DashboardOverview,
  Diagnostics,
  Job,
  Profile,
  ResumePlan,
  ResumeVersion,
  Skill,
  TailorSuggestion,
} from "../lib/types";

const EXPERIENCE_LINES = {
  bdl: [
    "Reduced message delivery latency to <100ms by optimizing WebSocket payload serialization and implementing per-room connection pooling, while maintaining AES-256-GCM + RSA-OAEP E2E encryption with zero server-side key exposure",
    "Eliminated man-in-the-middle attack surface by enforcing out-of-band RSA key fingerprint verification and per-room rate limiting (10 msg/s per user), blocking unauthorized session hijacking in integration tests",
    "Containerized Node.js WebSocket server and Express API with Docker Compose; wrote 15+ integration tests covering connection drops, key exchange failures, and message replay attacks",
  ].join("\n"),
  infosys: [
    "Engineered PyKV, an in-memory LRU cache engine with O(1) GET/SET via OrderedDict + asyncio.Lock; implemented AOF append-only persistence with atomic log compaction, reducing disk usage by 60% over 30-day operation",
    "Architected primary-to-standby replication with async best-effort forwarding; built real-time observability dashboard tracking hit-rate, memory utilization, and eviction patterns",
    "Built automated benchmarking pipeline with 20-way concurrent httpx load, characterizing true server throughput at 708 ops/s (1.41ms/op) vs. in-process dict baseline; identified serialization and connection pooling as primary latency drivers",
  ].join("\n"),
};

export const mockJobs: Job[] = [
  {
    id: 3,
    company: "Electronic Arts",
    roleTitle: "AI Full Stack Intern (Paid)",
    url: "",
    rawJd: "General Information\nLocations: Hyderabad, Telangana, India\nBuild AI-powered web tooling…",
    seniority: "Internship",
    domain: "AI/ML",
    requirementCount: 12,
  },
  {
    id: 4,
    company: "GitHub",
    roleTitle: "Software Engineering Intern",
    url: "",
    rawJd: "",
    seniority: "Internship",
    domain: "Developer Tools",
    requirementCount: 9,
  },
];

export const mockProfile: Profile = {
  fullName: "Alex Rivera",
  headline: "Software Developer | GSoC '26 Eval Call (Apache) | HackAp '25 Winner (100+ teams) | 1300+ Codeforces",
  email: "alex.rivera@example.com",
  phone: "+91 9876543210",
  location: "Hyderabad, India",
  website: "https://alexrivera.dev",
  github: "https://github.com/alex-rivera-dev",
  linkedin: "https://linkedin.com/in/alex-rivera",
  summary: "Software developer focused on systems, backend and applied AI.",
};

export const mockSkills: Skill[] = [
  { id: 1, canonicalName: "Rust", category: "language", aliases: [] },
  { id: 2, canonicalName: "Python", category: "language", aliases: [] },
  { id: 3, canonicalName: "TypeScript", category: "language", aliases: [] },
  { id: 4, canonicalName: "JavaScript", category: "language", aliases: [] },
  { id: 5, canonicalName: "C++", category: "language", aliases: [] },
  { id: 6, canonicalName: "Java", category: "language", aliases: [] },
  { id: 7, canonicalName: "SQL", category: "language", aliases: [] },
  { id: 8, canonicalName: "Tauri", category: "framework", aliases: [] },
  { id: 9, canonicalName: "React", category: "framework", aliases: [] },
  { id: 10, canonicalName: "FastAPI", category: "framework", aliases: [] },
  { id: 11, canonicalName: "Node.js", category: "framework", aliases: [] },
  { id: 12, canonicalName: "Next.js", category: "framework", aliases: [] },
  { id: 13, canonicalName: "Tailwind CSS", category: "framework", aliases: [] },
  { id: 14, canonicalName: "PostgreSQL", category: "database", aliases: [] },
  { id: 15, canonicalName: "MongoDB", category: "database", aliases: [] },
  { id: 16, canonicalName: "SQLite", category: "database", aliases: [] },
  { id: 17, canonicalName: "DynamoDB", category: "database", aliases: [] },
  { id: 18, canonicalName: "AWS", category: "cloud", aliases: [] },
  { id: 19, canonicalName: "Lambda", category: "cloud", aliases: [] },
  { id: 20, canonicalName: "Bedrock", category: "cloud", aliases: [] },
  { id: 21, canonicalName: "Docker", category: "devops", aliases: [] },
  { id: 22, canonicalName: "Git", category: "devops", aliases: [] },
  { id: 23, canonicalName: "GitHub Actions", category: "devops", aliases: [] },
  { id: 24, canonicalName: "Linux", category: "devops", aliases: [] },
  { id: 25, canonicalName: "NumPy", category: "tool", aliases: [] },
  { id: 26, canonicalName: "Pandas", category: "tool", aliases: [] },
];

export const mockPlan: ResumePlan = {
  composerVersion: 1,
  config: {
    targetPages: 1,
    maxProjects: 3,
    maxExperienceItems: 2,
    maxBulletsPerItem: 3,
    minFontSizePt: 9.5,
    templateId: "jake",
    paper: "a4",
  },
  header: {
    fullName: "Alex Rivera",
    headline: "Software Developer | GSoC '26 Eval Call (Apache) | HackAp '25 Winner (100+ teams) | 1300+ Codeforces",
    email: "alex.rivera@example.com",
    phone: "+91 9876543210",
    location: "Hyderabad, India",
    website: "https://alexrivera.dev",
    github: "https://github.com/alex-rivera-dev",
    linkedin: "https://linkedin.com/in/alex-rivera",
  },
  education: [
    {
      id: 1,
      institution: "Andhra University College Of Engineering Visakhapatnam",
      degree: "Bachelor of Technology",
      fieldOfStudy: "Computer Science & Systems Engineering",
      startDate: "2023-09",
      endDate: "2027-05",
      isCurrent: false,
    },
  ],
  experience: [
    {
      entityType: "experience",
      id: 2,
      title: "BDL (Bharat Dynamics Limited) — Project Intern",
      subtitle: "Visakhapatnam, India",
      startDate: "2025-06",
      endDate: "2025-07",
      isCurrent: false,
      description: EXPERIENCE_LINES.bdl,
      bullets: [],
      skills: ["Python", "Docker", "SQLite"],
      relevance: 0.9,
      evidenceCount: 3,
      excluded: false,
    },
    {
      entityType: "experience",
      id: 1,
      title: "Infosys Springboard — Python Intern",
      subtitle: "Remote",
      startDate: "2026-02",
      endDate: "2026-04",
      isCurrent: false,
      description: EXPERIENCE_LINES.infosys,
      bullets: [],
      skills: ["Python", "FastAPI"],
      relevance: 0.7,
      evidenceCount: 2,
      excluded: false,
    },
  ],
  projects: [
    {
      entityType: "project",
      id: 20,
      title: "CodeSensei",
      subtitle: "",
      startDate: null,
      endDate: null,
      isCurrent: false,
      description: [
        "Architected 4-layer Socratic reasoning pipeline (Beginner → Design → Pitfalls → Socratic) via structured JSON prompts to Amazon Bedrock Nova Lite; multi-turn conversation history with role alternation prevents context loss across follow-ups",
        "Optimized cross-region architecture (ap-south-2 Lambda → us-east-1 Bedrock) reducing model costs by 60% while maintaining sub-2s end-to-end latency; DynamoDB TTL enables 30-day per-user history at INR 0 idle cost",
        "Built auto-explain provider with 1.5s diagnostic debounce and CodeLens coverage for 10+ languages; serverless stack (SAM, Lambda, API Gateway) scales to zero with INR 0/month when inactive",
      ].join("\n"),
      bullets: [],
      skills: ["TypeScript", "AWS", "Bedrock"],
      relevance: 0.95,
      evidenceCount: 4,
      excluded: false,
    },
    {
      entityType: "project",
      id: 19,
      title: "WatchDog",
      subtitle: "",
      startDate: null,
      endDate: null,
      isCurrent: false,
      description: [
        "Built user-space background daemon implementing async producer-consumer pipeline with queue.Queue and SQLite executemany batch writes, eliminating synchronous I/O blocking on telemetry ingestion",
        "Replaced static threat thresholds with Exponential Moving Average (EMA) algorithm learning per-process resource baselines; flags anomalies at 3σ deviation with <5% false positive rate during 72-hour testing",
        "Enforced tamper-evident log integrity via canonical JSON serialization + SHA-256 hashing; implemented session-authenticated glassmorphic SOC dashboard with real-time threat feed and forensic audit trail",
      ].join("\n"),
      bullets: [],
      skills: ["Python", "SQLite"],
      relevance: 0.6,
      evidenceCount: 2,
      excluded: false,
    },
    {
      entityType: "project",
      id: 21,
      title: "Kairo",
      subtitle: "",
      startDate: null,
      endDate: null,
      isCurrent: false,
      description: [
        "Architected a local-first career workspace in Rust and Tauri 2 with decoupled domain modules and an append-only 10-migration SQLite WAL layer, verified through 77 unit and integration tests",
        "Built a deterministic constraint solver and matching engine computing coverage against JDs via pure functions, enforcing zero-fabrication metrics and technology diff validation on rewrites",
        "Integrated headless ATS-safe PDF compilation via portable Tectonic LaTeX binary, running unlocked async I/O to guarantee zero UI thread blocking during compilation",
      ].join("\n"),
      bullets: [],
      skills: ["Rust", "Tauri", "SQL"],
      relevance: 0.8,
      evidenceCount: 3,
      excluded: false,
    },
  ],
  achievements: [
    {
      id: 1,
      title: "GSoC '26 Eval Call (Apache)",
      issuer: "Apache Software Foundation",
      description: "Selected for the evaluation call after the proposal round.",
      achievedOn: "2026-05-01",
      excluded: false,
    },
    {
      id: 2,
      title: "HackAp '25 Winner",
      issuer: "HackAp",
      description: "1st place among 100+ teams.",
      achievedOn: "2025-11-20",
      excluded: false,
    },
  ],
  skills: mockSkills.map((s) => s.canonicalName),
  skillsGrouped: [
    { category: "Languages", skills: ["Rust", "Python", "TypeScript", "JavaScript", "C++", "Java", "SQL"] },
    { category: "Frameworks", skills: ["Tauri", "React", "FastAPI", "Node.js", "Next.js", "Tailwind CSS"] },
    { category: "Databases", skills: ["PostgreSQL", "MongoDB", "SQLite", "DynamoDB"] },
    { category: "Cloud", skills: ["AWS", "Lambda", "Bedrock"] },
    { category: "DevOps", skills: ["Docker", "Git", "GitHub Actions", "Linux"] },
    { category: "Tools", skills: ["NumPy", "Pandas"] },
  ],
  excludedSkills: [],
  estimatedLines: 58,
  fitsOnePage: true,
  warnings: [],
};

export const mockSuggestions: TailorSuggestion[] = [];

export const mockVersions: ResumeVersion[] = [];

export const mockApplications: Application[] = [
  {
    id: 1,
    jobId: 3,
    resumeVersionId: null,
    company: "Electronic Arts",
    role: "AI Full Stack Intern",
    url: "",
    status: "applied",
    appliedDate: "2026-09-10",
    nextAction: "Follow up next week",
    notes: "Referred by a senior dev on the team.",
  },
  {
    id: 2,
    jobId: 4,
    resumeVersionId: null,
    company: "GitHub",
    role: "Software Engineering Intern",
    url: "",
    status: "interview",
    appliedDate: "2026-09-01",
    nextAction: "Tech round prep",
    notes: "",
  },
  {
    id: 3,
    jobId: null,
    resumeVersionId: null,
    company: "Stripe",
    role: "Backend Intern",
    url: "",
    status: "wishlist",
    appliedDate: null,
    nextAction: "",
    notes: "",
  },
];

export const mockDiagnostics: Diagnostics = {
  appVersion: "3.0.0",
  schemaVersion: 10,
  latestMigration: "0010_applications",
  sqliteVersion: "3.46.0",
  dbPath: "%APPDATA%/com.kairo.app/kairo.db",
  migrationsApplied: ["0001_init", "0002_career_vault", "0010_applications"],
};

export const mockDashboard: DashboardOverview = {
  counts: {
    projects: 3,
    experiences: 2,
    education: 1,
    certifications: 2,
    achievements: 4,
    skills: 26,
    evidenceTotal: 18,
    evidenceVerified: 11,
    evidenceUnverified: 7,
    canonicalBullets: 9,
    bulletsApproved: 8,
    claimRules: 3,
    jobs: 2,
    jobsWithMatch: 1,
    jobsWithPlan: 1,
    pdfsCompiled: 2,
    resumeVersions: 1,
    suggestionsPending: 2,
    applications: 3,
    applicationsActive: 2,
  },
  evidenceNeedingReview: [
    {
      id: 1,
      entityType: "project",
      entityId: 20,
      entityLabel: "CodeSensei",
      kind: "metric",
      title: "60% model cost reduction",
      reference: "benchmark-notes.md",
      createdAt: "2026-09-14T10:00:00",
    },
    {
      id: 2,
      entityType: "experience",
      entityId: 2,
      entityLabel: "BDL — Project Intern",
      kind: "repository",
      title: "Secure messenger repo",
      reference: "github.com/alex-rivera-dev/messenger",
      createdAt: "2026-09-13T18:30:00",
    },
  ],
  recentActivity: [
    { kind: "pdf_exported", refType: "job", refId: 3, label: "PDF compiled", detail: "AI Full Stack Intern · 1 page", at: "2026-09-17T20:12:00" },
    { kind: "plan_saved", refType: "job", refId: 3, label: "Resume plan saved", detail: "AI Full Stack Intern", at: "2026-09-17T19:58:00" },
    { kind: "application_created", refType: "application", refId: 1, label: "Application tracked", detail: "Electronic Arts · Applied", at: "2026-09-15T09:20:00" },
    { kind: "job_created", refType: "job", refId: 4, label: "Job workspace created", detail: "GitHub · SWE Intern", at: "2026-09-14T16:40:00" },
  ],
};
